#!/usr/bin/bash

dotdir="$HOME/dotfiles"
if [[ -z $1 ]]; then
	dotdir=$1
fi

gsettings set org.gnome.desktop.peripherals.mouse accel-profile flat

sudo apt install \
	galternatives\
	gnome-tweaks\
	neofetch\
	build-essential\
	git cmake clang clangd ninja-build\
	libllvm11 curl\
	neovim gnome-software\
  libxcb1-dev libxcb-render0-dev libxcb-xfixes0-dev libxcb-shape0-dev libfontconfig-dev\
  nodejs nasm ocaml\
  libxss1 libappindicator1 libindicator7\
  vulkan-validationlayers-dev vulkan-utils libvulkan-dev libglfw3-dev libassimp-dev
  -y


if ! [ -x "$(command -v google-chrome)" ]; then
  wget -O chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  sudo apt install ./chrome.deb
  rm ./chrome.deb
fi


if ! [ -x "$(command -v discord)" ]; then
  wget -O discord.deb "https://discordapp.com/api/download?platform=linux&format=deb"
  sudo apt install ./discord.deb -y
  rm ./discord.deb
fi


git config --global user.email "atilkurtulmus@gmail.com"
git config --global credential.helper "cache --timeout=999999999"
git clone https://github.com/atkurtul/dotfiles
cd dotfiles


curl -sLf https://spacevim.org/install.sh | bash
curl https://sh.rustup.rs -sSf | sh -s -- -y
~/.cargo/bin/cargo install alacritty
sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator ~/.cargo/bin/alacritty 100

sudo apt purge snapd -y


ln -sf $dotdir/.alacritty.yml ~/.alacritty.yml
ln -sf $dotdir/.clang-format.txt ~/.clang-format.txt
ln -sf $dotdir/.gdbinit ~/.gdbinit
ln -sf $dotdir/.tmux.conf ~/.tmux.conf

mkdir -p ~/.config/nvim
ln -sf $HOME/dotfiles/nvim ~/.config/nvim/init.vim
mkdir -p ~/.SpaceVim.d
ln -sf $HOME/dotfiles/svim ~/.SpaceVim.d/init.toml
mkdir -p ~/.emacs.d
ln -sf $HOME/dotfiles/emacs ~/.emacs.d/init.el

mkdir -p ~/.themes
mkdir -p ~/.icons
git clone https://github.com/dracula/gtk.git
mv gtk ~/.themes/Dracula

wget https://github.com/dracula/gtk/files/5214870/Dracula.zip
unzip Dracula.zip
mv Dracula ~/.icons
rm Dracula.zip
rm -rf Dracula
rm -rf gtk
gsettings set org.gnome.desktop.interface gtk-theme "Dracula"
gsettings set org.gnome.desktop.wm.preferences theme "Dracula"
gsettings set org.gnome.desktop.interface icon-theme "Dracula"

cd ~/.SpaceVim/bundle/vimproc.vim
make

echo "source $HOME/dotfiles/init.sh" >> ~/.bashrc
