#!/usr/bin/perl

$asm = `objdump -d -Mintel @ARGV[0]`;

if (@ARGV >= 2) {
  foreach $arg (@ARGV[1..@ARGV-1]) {
    if ("$asm\n" =~ /\d+ \<$arg(?:@.*)?\>:((.|\n)*?)\n\n/g) {
      $line = $1;
      $line  =~ s/^\s*\w+:\s+([a-f0-9]{2}\s)*\s+(.*$)/\t$2/gm;
      print "$arg:\n$line\n";
    } else {
      print "No match for <$arg>\n";
    }
  }
} else {
  print "$asm\n";
}
