#!/usr/bin/perl

if(!(@ARGV[0])) {
  print "Invalid size\n";
  exit;
}

$cap="?:";

if (@ARGV[1] eq "-c") {
  $cap="";
}

my @set = ('0' ..'9', 'A' .. 'Z', 'a'..'z');
sub rstr {
  (my $len) = @_;
  my $str = join '' => map $set[rand @set], 1 .. $len;
}

sub rexpr {
  (my $l) = @_;
  my $r = rstr 1;
  my $n = int(rand 6);
  if(0 == $n){ return "$l$r";  } # cat
  if(4 <= $n){ return "($cap$l|$r)"; } # |
  if(1 == $n){ return "($cap$l+)"; }   # +
  if(2 == $n){ return "($cap$l*)"; } # *
  if(3 == $n){ return "($cap$l?)"; } # ?
  return $l;
}

$x = rstr 1;
$i=0;
while($i++ < @ARGV[0]){
  $x=rexpr$x;
}

print "$x\n";
